# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MyGLFWProject_config = debug

else ifeq ($(config),release)
  MyGLFWProject_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MyGLFWProject

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MyGLFWProject:
ifneq (,$(MyGLFWProject_config))
	@echo "==== Building MyGLFWProject ($(MyGLFWProject_config)) ===="
	@${MAKE} --no-print-directory -C . -f MyGLFWProject.make config=$(MyGLFWProject_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MyGLFWProject.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MyGLFWProject"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"